version: '3.7'

services:
  main:
    container_name: main
    image: xmmendezy/dt_core:latest
    restart: always
    volumes:
      - main:/usr/src/app
    ports:
      - 80:9000
    env_file:
      - .env.production
    networks:
      - webnet
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:12
    networks:
      - webnet
    env_file:
      - .env.test
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  webnet:
volumes:
  pgdata:
  main:
