// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    FasChevronLeft: typeof import('~icons/fa-solid/chevron-left')['default']
    FasChevronRight: typeof import('~icons/fa-solid/chevron-right')['default']
    FasEnvelope: typeof import('~icons/fa-solid/envelope')['default']
    Input: typeof import('./src/components/Input.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Switch: typeof import('./src/components/Switch.vue')['default']
  }
}

export { }
