// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AdminHeader: typeof import('./src/components/AdminHeader.vue')['default']
    FasCheck: typeof import('~icons/fa-solid/check')['default']
    FasEnvelopeOpenText: typeof import('~icons/fa-solid/envelope-open-text')['default']
    FasExclamationCircle: typeof import('~icons/fa-solid/exclamation-circle')['default']
    FasPlus: typeof import('~icons/fa-solid/plus')['default']
    FasTimes: typeof import('~icons/fa-solid/times')['default']
    FasUser: typeof import('~icons/fa-solid/user')['default']
    MainHeader: typeof import('./src/components/MainHeader.vue')['default']
    VuePaycard: typeof import('./src/components/VuePaycard.vue')['default']
  }
}

export { }
