// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AdminHeader: typeof import('./src/components/AdminHeader.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MainHeader: typeof import('./src/components/MainHeader.vue')['default']
    'MainHeader copy': typeof import('./src/components/MainHeader copy.vue')['default']
  }
}

export { }
