// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Image: typeof import('./src/components/Image.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PointSVG: typeof import('./src/components/PointSVG.vue')['default']
    Tradingview: typeof import('./src/components/Tradingview.vue')['default']
  }
}

export { }
